### ISSUE TITLE
rails db:migrate not working

### ISSUE THREAD

**Issue by 0tt049** [0tt049/dev4dev#17]
## Context
`rails db:drop` works
`rails db:create` works
`rails db:migrate` not working...

## Show error
```
[otavio@otavio-manjaro] ~/code/0tt049/dev4dev (master) 
❯ rails db:drop
Dropped database 'dev4dev_development'
Dropped database 'dev4dev_test'

[otavio@otavio-manjaro] ~/code/0tt049/dev4dev (master) 
❯ rails db:create
Created database 'dev4dev_development'
Created database 'dev4dev_test'

[otavio@otavio-manjaro] ~/code/0tt049/dev4dev (master) 
❯ rails db:migrate
== 20230301185059 DeviseCreateUsers: migrating ================================
-- create_table(:users)
   -> 0.0057s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0022s
-- add_index(:users, :reset_password_token, {:unique=>true})
   -> 0.0017s
== 20230301185059 DeviseCreateUsers: migrated (0.0098s) =======================

== 20230301190753 AddNameToUsers: migrating ===================================
-- add_column(:users, :name, :string)
   -> 0.0021s
== 20230301190753 AddNameToUsers: migrated (0.0021s) ==========================

== 20230301195749 CreateProjects: migrating ===================================
-- create_table(:projects)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "slots" does not exist
/home/otavio/code/0tt049/dev4dev/db/migrate/20230301195749_create_projects.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "slots" does not exist
/home/otavio/code/0tt049/dev4dev/db/migrate/20230301195749_create_projects.rb:3:in `change'

Caused by:
PG::UndefinedTable: ERROR:  relation "slots" does not exist
/home/otavio/code/0tt049/dev4dev/db/migrate/20230301195749_create_projects.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

## Action

Please check running app on your machines
@vcanedo @praecipito @Gmmuoio

**Comment by 0tt049** [comment]
> == 20230301195749 CreateProjects: migrating ===================================
> -- create_table(:projects)
> rails aborted!
> StandardError: An error has occurred, this and all later migrations canceled:
> 
> PG::UndefinedTable: ERROR:  relation "slots" does not exist
> /home/otavio/code/0tt049/dev4dev/db/migrate/20230301195749_create_projects.rb:3:in `change'

Error happens when `create_table(:projects)`. It tries to find "slots" but `rails db:migrate` script hasn't run `create_table(:slots)` yet. 

So... how do we make `rails db:migrate` create `user` **and** `slot` **before** `project` ?
